// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcgkqcbzhvexplyfxonx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjZ2txY2J6aHZleHBseWZ4b254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODYyMTAsImV4cCI6MjA2NjM2MjIxMH0.sBGubHmHE2OglAT4AxFX9MhcS4aDJU_YHfqH_pM-R10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);